apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ required "a valid namespace is required!" .Values.service.namespace }}
{{ if eq .Values.service.plan "Alias" }}
  annotations:
    ibmcloud.ibm.com/instanceId: {{ required "A valid instanceId is required when service.plan is set to Alias" .Values.service.instanceId | quote }}
{{ end }}
spec:
  plan: {{ required "A valid service plan is required." .Values.service.plan }}
  serviceClass: {{ .Values.service.serviceClass }}
  context:
    region: {{ .Values.service.context.region }}
    resourcegroup: {{ .Values.service.context.resourceGroup }}
  externalName:  {{ .Values.service.externalName }}
{{ if .Values.parameters }}
  parameters:
    {{- range $key, $val := .Values.service.parameters }}
    {{ $key }}: {{ $val }}
    {{- end }}
{{ end }}
---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Binding
metadata:
  name: binding-{{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
{{ if eq .Values.binding.alias true }}
  annotations:
    ibmcloud.ibm.com/keyId: {{ required "A valid keyId is required when binding.alias is set to true" .Values.binding.keyId | quote }}
{{ end }}
spec:
  serviceName: {{ .Values.service.name }}
  role: Manager
  serviceNamespace: {{ .Values.service.namespace }}